version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
    groups:
      experimental-golang-deps:
        patterns:
          - "golang.org/x/*"
      testing-deps:
        patterns:
          - "github.com/onsi/ginkgo/v2"
          - "github.com/onsi/gomega"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
