# Documentation https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
before:
  hooks:
    - go mod tidy

builds:
  - binary: flow
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags: >-
      -s -w
      -X "github.com/flowexec/flow/cmd/internal/version.gitCommit={{ .Commit }}"
      -X "github.com/flowexec/flow/cmd/internal/version.version={{ .Version }}"
      -X "github.com/flowexec/flow/cmd/internal/version.buildDate={{ .Date }}"

gomod:
  proxy: false

archives:
  - formats: [ 'tar.gz' ]
    files:
      - LICENSE
      - README.md
      - scripts/completions
    name_template: >-
      {{ .Binary }}_
      {{- .Tag }}_
      {{- .Os }}_
      {{- .Arch }}

homebrew_casks:
  - name: flow
    binary: flow
    homepage: https://flowexec.io
    license: Apache-2.0
    repository:
      owner: flowexec
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_FLOW_GITHUB_TOKEN }}"
    completions:
      bash: scripts/completions/flow.bash
      zsh: scripts/completions/flow.zsh
      fish: scripts/completions/flow.fish
#    dependencies:
#      - cask: xclip # Required for clipboard support, only linux, so I need to figure out to get this to skip macOS
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flow"]
          end

# Docker builds migrated to ko via flow executables
# Use: flow build multiarch --dry-run (local testing)
#      flow publish docker --tag=vX.Y.Z (CI only)

changelog:
  sort: asc
  groups:
  - title: "New features"
    regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    order: 0
  - title: "Bug fixes"
    regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    order: 1
  - title: "Documentation updates"
    regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
    order: 2
  - title: "Miscellaneous"
    order: 999
