env:
  - GO111MODULE=auto

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completions.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w

universal_binaries:
  - replace: false

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^Merge pull request"
      - "^Merge branch"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*

brews:
  - repository:
      owner: jahvon
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    goarm: "7"
    homepage: https://github.com/jahvon/flow
    description: Configurable local workflow manager.
    license: Apache 2.0
    test: |
      system "#{bin}/flow version"
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "flow"
      bash_completion.install "completions/flow.bash" => "flow"
      zsh_completion.install "completions/flow.zsh" => "_flow"
      fish_completion.install "completions/flow.fish"

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/jahvon/flow
    description: Configurable local workflow manager.
    maintainer: Jahvon Dockery <jahvondockery@gmail.com>
    license: Apache 2.0
    vendor: jahvon
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/flow.bash
        dst: /usr/share/bash-completion/completions/flow
        file_info:
          mode: 0644
      - src: ./completions/flow.fish
        dst: /usr/share/fish/vendor_completions.d/flow.fish
        file_info:
          mode: 0644
      - src: ./completions/flow.zsh
        dst: /usr/share/zsh/vendor-completions/_flow
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/flow/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    recommends:
      - golang
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

publishers:
  - name: fury.io
    ids:
      - packages
    env:
      - "FURY_TOKEN={{ .Env.FURY_TOKEN }}"
    cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}

release:
  footer: |
    **Full Changelog**: https://github.com/jahvon/flow/compare/{{ .PreviousTag }}...{{ .Tag }}
