github_checks:
  annotations: false
coverage:
  range: "50...100"
  status:
    project:
      default:
        target: auto
        threshold: 3
        if_ci_failed: success
        informational: true
        only_pulls: true
    patch:
      default:
          target: auto
          threshold: 0
          if_ci_failed: success
          informational: true
          only_pulls: true
ignore:
  - "**/*.gen.go" # ignore generated code
  - "tools/**" # ignore tools directory
