// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/flowexec/flow/v2/pkg/cache (interfaces: TemplateCache)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_template_cache.go -package=mocks github.com/flowexec/flow/v2/pkg/cache TemplateCache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	executable "github.com/flowexec/flow/v2/types/executable"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateCache is a mock of TemplateCache interface.
type MockTemplateCache struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateCacheMockRecorder
}

// MockTemplateCacheMockRecorder is the mock recorder for MockTemplateCache.
type MockTemplateCacheMockRecorder struct {
	mock *MockTemplateCache
}

// NewMockTemplateCache creates a new mock instance.
func NewMockTemplateCache(ctrl *gomock.Controller) *MockTemplateCache {
	mock := &MockTemplateCache{ctrl: ctrl}
	mock.recorder = &MockTemplateCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateCache) EXPECT() *MockTemplateCacheMockRecorder {
	return m.recorder
}

// GetTemplate mocks base method.
func (m *MockTemplateCache) GetTemplate(arg0 string) (*executable.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", arg0)
	ret0, _ := ret[0].(*executable.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockTemplateCacheMockRecorder) GetTemplate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockTemplateCache)(nil).GetTemplate), arg0)
}

// GetTemplateList mocks base method.
func (m *MockTemplateCache) GetTemplateList() (executable.TemplateList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateList")
	ret0, _ := ret[0].(executable.TemplateList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateList indicates an expected call of GetTemplateList.
func (mr *MockTemplateCacheMockRecorder) GetTemplateList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateList", reflect.TypeOf((*MockTemplateCache)(nil).GetTemplateList))
}

// Update mocks base method.
func (m *MockTemplateCache) Update() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update")
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTemplateCacheMockRecorder) Update() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTemplateCache)(nil).Update))
}
