$schema: "http://json-schema.org/draft-07/schema#"
$id: "https://raw.githubusercontent.com/flowexec/flow/HEAD/types/workspace/schema.yaml"

title: Workspace
description: |
  Configuration for a workspace in the Flow CLI.
  This configuration is used to define the settings for a workspace.
  Every workspace has a workspace config file named `flow.yaml` in the root of the workspace directory.

definitions:
  ExecutableFilter:
    type: object
    properties:
      included:
        type: array
        items:
          type: string
        description: |
          A list of directories or file patterns to include in the executable search.
          Supports directory paths (e.g., "src/", "scripts/") and glob patterns for filenames (e.g., "*.test.flow", "example*").
        default: []
      excluded:
        type: array
        items:
          type: string
        description: |
          A list of directories or file patterns to exclude from the executable search.
          Supports directory paths (e.g., "node_modules/", "vendor/") and glob patterns for filenames (e.g., "*.js.flow", "*temp*").
          Common exclusions like node_modules/, vendor/, third_party/, external/, and *.js.flow are excluded by default.
        default: []
  VerbAliases:
    type: object
    description: |
      A map of executable verbs to valid aliases. This allows you to use custom aliases for exec commands in the workspace.
      Setting this will override all of the default flow command aliases. The verbs and its mapped aliases must be valid flow verbs.
      
      If set to an empty object, verb aliases will be disabled.
    additionalProperties:
      type: array
      items:
          type: string

type: object
properties:
  tags:
    $ref: '../common/schema.yaml#/definitions/Tags'
    goJSONSchema:
      type: "common.Tags"
      imports: [ "github.com/flowexec/flow/types/common" ]
    default: []
  executables:
    $ref: '#/definitions/ExecutableFilter'
  displayName:
    type: string
    description: The display name of the workspace. This is used in the interactive UI.
    default: ""
  description:
    type: string
    description: A description of the workspace. This description is rendered as markdown in the interactive UI.
    default: ""
  descriptionFile:
    type: string
    description: A path to a markdown file that contains the description of the workspace.
    default: ""
  verbAliases:
    $ref: '#/definitions/VerbAliases'
    goJSONSchema:
      type: "map[string][]string"
      nillable: false
  envFiles:
    type: array
    items:
      type: string
    description: |
      A list of environment variable files to load for the workspace. These files should contain key-value pairs of environment variables.
      By default, the `.env` file in the workspace root is loaded if it exists.
    default: []
  assignedName:
    type: string
    goJSONSchema:
      identifier: assignedName
    default: ""
  location:
    type: string
    goJSONSchema:
      identifier: location
    default: ""
