// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package workspace

import "github.com/flowexec/flow/types/common"

type ExecutableFilter struct {
	// A list of directories or file patterns to exclude from the executable search.
	// Supports directory paths (e.g., "node_modules/", "vendor/") and glob patterns
	// for filenames (e.g., "*.js.flow", "*temp*").
	// Common exclusions like node_modules/, vendor/, third_party/, external/, and
	// *.js.flow are excluded by default.
	//
	Excluded []string `json:"excluded,omitempty" yaml:"excluded,omitempty" mapstructure:"excluded,omitempty"`

	// A list of directories or file patterns to include in the executable search.
	// Supports directory paths (e.g., "src/", "scripts/") and glob patterns for
	// filenames (e.g., "*.test.flow", "example*").
	//
	Included []string `json:"included,omitempty" yaml:"included,omitempty" mapstructure:"included,omitempty"`
}

// A map of executable verbs to valid aliases. This allows you to use custom
// aliases for exec commands in the workspace.
// Setting this will override all of the default flow command aliases. The verbs
// and its mapped aliases must be valid flow verbs.
//
// If set to an empty object, verb aliases will be disabled.
type VerbAliases map[string][]string

// Configuration for a workspace in the Flow CLI.
// This configuration is used to define the settings for a workspace.
// Every workspace has a workspace config file named `flow.yaml` in the root of the
// workspace directory.
type Workspace struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations WorkspaceAnnotations `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// assignedName corresponds to the JSON schema field "assignedName".
	assignedName string `json:"assignedName,omitempty" yaml:"assignedName,omitempty" mapstructure:"assignedName,omitempty"`

	// A description of the workspace. This description is rendered as markdown in the
	// interactive UI.
	Description string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// A path to a markdown file that contains the description of the workspace.
	DescriptionFile string `json:"descriptionFile,omitempty" yaml:"descriptionFile,omitempty" mapstructure:"descriptionFile,omitempty"`

	// The display name of the workspace. This is used in the interactive UI.
	DisplayName string `json:"displayName,omitempty" yaml:"displayName,omitempty" mapstructure:"displayName,omitempty"`

	// A list of environment variable files to load for the workspace. These files
	// should contain key-value pairs of environment variables.
	// By default, the `.env` file in the workspace root is loaded if it exists.
	//
	EnvFiles []string `json:"envFiles,omitempty" yaml:"envFiles,omitempty" mapstructure:"envFiles,omitempty"`

	// Executables corresponds to the JSON schema field "executables".
	Executables *ExecutableFilter `json:"executables,omitempty" yaml:"executables,omitempty" mapstructure:"executables,omitempty"`

	// The git ref (branch or tag name) that was specified when the workspace was
	// added from a git URL.
	// Used by `flow workspace update` to checkout the correct ref after pulling.
	//
	GitRef string `json:"gitRef,omitempty" yaml:"gitRef,omitempty" mapstructure:"gitRef,omitempty"`

	// The type of git ref specified when the workspace was added.
	// Either "branch" or "tag". Empty if no ref was specified.
	//
	GitRefType WorkspaceGitRefType `json:"gitRefType,omitempty" yaml:"gitRefType,omitempty" mapstructure:"gitRefType,omitempty"`

	// The git remote URL for the workspace. This is set automatically when a
	// workspace is added from a git URL.
	// Used by `flow workspace update` to pull the latest changes.
	//
	GitRemote string `json:"gitRemote,omitempty" yaml:"gitRemote,omitempty" mapstructure:"gitRemote,omitempty"`

	// location corresponds to the JSON schema field "location".
	location string `json:"location,omitempty" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags WorkspaceTags `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// VerbAliases corresponds to the JSON schema field "verbAliases".
	VerbAliases *WorkspaceVerbAliases `json:"verbAliases,omitempty" yaml:"verbAliases,omitempty" mapstructure:"verbAliases,omitempty"`
}

type WorkspaceAnnotations common.Annotations

type WorkspaceGitRefType string

const WorkspaceGitRefTypeBlank WorkspaceGitRefType = ""
const WorkspaceGitRefTypeBranch WorkspaceGitRefType = "branch"
const WorkspaceGitRefTypeTag WorkspaceGitRefType = "tag"

type WorkspaceTags common.Tags

type WorkspaceVerbAliases map[string][]string
