// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/flowexec/flow/pkg/store (interfaces: DataStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_data_store.go -package=mocks github.com/flowexec/flow/pkg/store DataStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	store "github.com/flowexec/flow/pkg/store"
	gomock "go.uber.org/mock/gomock"
)

// MockDataStore is a mock of DataStore interface.
type MockDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockDataStoreMockRecorder
}

// MockDataStoreMockRecorder is the mock recorder for MockDataStore.
type MockDataStoreMockRecorder struct {
	mock *MockDataStore
}

// NewMockDataStore creates a new mock instance.
func NewMockDataStore(ctrl *gomock.Controller) *MockDataStore {
	mock := &MockDataStore{ctrl: ctrl}
	mock.recorder = &MockDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataStore) EXPECT() *MockDataStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDataStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDataStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDataStore)(nil).Close))
}

// CreateProcessBucket mocks base method.
func (m *MockDataStore) CreateProcessBucket(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProcessBucket", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProcessBucket indicates an expected call of CreateProcessBucket.
func (mr *MockDataStoreMockRecorder) CreateProcessBucket(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProcessBucket", reflect.TypeOf((*MockDataStore)(nil).CreateProcessBucket), arg0)
}

// DeleteBackgroundRun mocks base method.
func (m *MockDataStore) DeleteBackgroundRun(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBackgroundRun", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBackgroundRun indicates an expected call of DeleteBackgroundRun.
func (mr *MockDataStoreMockRecorder) DeleteBackgroundRun(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackgroundRun", reflect.TypeOf((*MockDataStore)(nil).DeleteBackgroundRun), arg0)
}

// DeleteCacheEntry mocks base method.
func (m *MockDataStore) DeleteCacheEntry(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCacheEntry", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCacheEntry indicates an expected call of DeleteCacheEntry.
func (mr *MockDataStoreMockRecorder) DeleteCacheEntry(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCacheEntry", reflect.TypeOf((*MockDataStore)(nil).DeleteCacheEntry), arg0)
}

// DeleteExecutionHistory mocks base method.
func (m *MockDataStore) DeleteExecutionHistory(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExecutionHistory", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExecutionHistory indicates an expected call of DeleteExecutionHistory.
func (mr *MockDataStoreMockRecorder) DeleteExecutionHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExecutionHistory", reflect.TypeOf((*MockDataStore)(nil).DeleteExecutionHistory), arg0)
}

// DeleteProcessBucket mocks base method.
func (m *MockDataStore) DeleteProcessBucket(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProcessBucket", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProcessBucket indicates an expected call of DeleteProcessBucket.
func (mr *MockDataStoreMockRecorder) DeleteProcessBucket(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProcessBucket", reflect.TypeOf((*MockDataStore)(nil).DeleteProcessBucket), arg0)
}

// DeleteProcessVar mocks base method.
func (m *MockDataStore) DeleteProcessVar(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProcessVar", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProcessVar indicates an expected call of DeleteProcessVar.
func (mr *MockDataStoreMockRecorder) DeleteProcessVar(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProcessVar", reflect.TypeOf((*MockDataStore)(nil).DeleteProcessVar), arg0, arg1)
}

// GetAllProcessVars mocks base method.
func (m *MockDataStore) GetAllProcessVars(arg0 string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProcessVars", arg0)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProcessVars indicates an expected call of GetAllProcessVars.
func (mr *MockDataStoreMockRecorder) GetAllProcessVars(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProcessVars", reflect.TypeOf((*MockDataStore)(nil).GetAllProcessVars), arg0)
}

// GetBackgroundRun mocks base method.
func (m *MockDataStore) GetBackgroundRun(arg0 string) (store.BackgroundRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackgroundRun", arg0)
	ret0, _ := ret[0].(store.BackgroundRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackgroundRun indicates an expected call of GetBackgroundRun.
func (mr *MockDataStoreMockRecorder) GetBackgroundRun(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackgroundRun", reflect.TypeOf((*MockDataStore)(nil).GetBackgroundRun), arg0)
}

// GetCacheEntry mocks base method.
func (m *MockDataStore) GetCacheEntry(arg0 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheEntry", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCacheEntry indicates an expected call of GetCacheEntry.
func (mr *MockDataStoreMockRecorder) GetCacheEntry(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheEntry", reflect.TypeOf((*MockDataStore)(nil).GetCacheEntry), arg0)
}

// GetExecutionHistory mocks base method.
func (m *MockDataStore) GetExecutionHistory(arg0 string, arg1 int) ([]store.ExecutionRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionHistory", arg0, arg1)
	ret0, _ := ret[0].([]store.ExecutionRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutionHistory indicates an expected call of GetExecutionHistory.
func (mr *MockDataStoreMockRecorder) GetExecutionHistory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionHistory", reflect.TypeOf((*MockDataStore)(nil).GetExecutionHistory), arg0, arg1)
}

// GetProcessVar mocks base method.
func (m *MockDataStore) GetProcessVar(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessVar", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessVar indicates an expected call of GetProcessVar.
func (mr *MockDataStoreMockRecorder) GetProcessVar(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessVar", reflect.TypeOf((*MockDataStore)(nil).GetProcessVar), arg0, arg1)
}

// GetProcessVarKeys mocks base method.
func (m *MockDataStore) GetProcessVarKeys(arg0 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessVarKeys", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessVarKeys indicates an expected call of GetProcessVarKeys.
func (mr *MockDataStoreMockRecorder) GetProcessVarKeys(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessVarKeys", reflect.TypeOf((*MockDataStore)(nil).GetProcessVarKeys), arg0)
}

// ListBackgroundRuns mocks base method.
func (m *MockDataStore) ListBackgroundRuns() ([]store.BackgroundRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackgroundRuns")
	ret0, _ := ret[0].([]store.BackgroundRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackgroundRuns indicates an expected call of ListBackgroundRuns.
func (mr *MockDataStoreMockRecorder) ListBackgroundRuns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackgroundRuns", reflect.TypeOf((*MockDataStore)(nil).ListBackgroundRuns))
}

// ListExecutionRefs mocks base method.
func (m *MockDataStore) ListExecutionRefs() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExecutionRefs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExecutionRefs indicates an expected call of ListExecutionRefs.
func (mr *MockDataStoreMockRecorder) ListExecutionRefs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExecutionRefs", reflect.TypeOf((*MockDataStore)(nil).ListExecutionRefs))
}

// RecordExecution mocks base method.
func (m *MockDataStore) RecordExecution(arg0 store.ExecutionRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordExecution", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordExecution indicates an expected call of RecordExecution.
func (mr *MockDataStoreMockRecorder) RecordExecution(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordExecution", reflect.TypeOf((*MockDataStore)(nil).RecordExecution), arg0)
}

// SaveBackgroundRun mocks base method.
func (m *MockDataStore) SaveBackgroundRun(arg0 store.BackgroundRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBackgroundRun", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBackgroundRun indicates an expected call of SaveBackgroundRun.
func (mr *MockDataStoreMockRecorder) SaveBackgroundRun(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBackgroundRun", reflect.TypeOf((*MockDataStore)(nil).SaveBackgroundRun), arg0)
}

// SetCacheEntry mocks base method.
func (m *MockDataStore) SetCacheEntry(arg0 string, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCacheEntry", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCacheEntry indicates an expected call of SetCacheEntry.
func (mr *MockDataStoreMockRecorder) SetCacheEntry(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCacheEntry", reflect.TypeOf((*MockDataStore)(nil).SetCacheEntry), arg0, arg1)
}

// SetProcessVar mocks base method.
func (m *MockDataStore) SetProcessVar(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProcessVar", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProcessVar indicates an expected call of SetProcessVar.
func (mr *MockDataStoreMockRecorder) SetProcessVar(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProcessVar", reflect.TypeOf((*MockDataStore)(nil).SetProcessVar), arg0, arg1, arg2)
}
